"""reaname postion_name to position_names, add user_profiles table

Revision ID: be54919f8c32
Revises: 01a0a87636a0
Create Date: 2026-07-07 16:54:34.986909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be54919f8c32'
down_revision: Union[str, None] = '01a0a87636a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('address1', sa.String(length=100), nullable=True),
    sa.Column('address2', sa.String(length=100), nullable=True),
    sa.Column('address3', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_constraint('users_position_id_fkey', 'users', type_='foreignkey')
    op.drop_table('position_name')
    op.create_foreign_key(None, 'users', 'position_names', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_position_id_fkey', 'users', 'position_name', ['position_id'], ['id'])
    op.create_table('position_name',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='position_name_pkey'),
    sa.UniqueConstraint('name', name='position_name_name_key')
    )
    op.drop_table('user_profiles')
    op.drop_table('position_names')
    # ### end Alembic commands ###
