"""add order column to position_names

Revision ID: e25885fc4401
Revises: be54919f8c32
Create Date: 2026-07-11 20:42:26.087135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25885fc4401'
down_revision: Union[str, None] = 'be54919f8c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_names', sa.Column('order', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position_names', 'order')
    # ### end Alembic commands ###
